// build-final.mjs — generates final/ (the Liferay handoff package) from source.
//
// Run: node scripts/build-final.mjs
//
// Regenerate this any time index.html / styles.css / tokens.css / app.js /
// content.js change — final/ is BUILT, not hand-maintained, so the three
// fragment fields (HTML/CSS/JS) can't drift from the working prototype (see
// LIFERAY-CONVERSION-PLAYBOOK.md §3). Do not hand-edit files inside final/.
'use strict';

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT  = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT   = path.join(ROOT, 'final');
const NAME  = 'welcome-baby';

const readLF = (p) => fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');

// ── 1. HTML field: the wb_root element's contents, scripts stripped ───────────
let html = readLF(path.join(ROOT, 'index.html'));
const rootOpenIdx  = html.indexOf('<div class="wb_root" data-wb-root>');
const rootCloseTag = '\t</div>\n</body>';
const rootCloseIdx = html.indexOf(rootCloseTag);
if (rootOpenIdx === -1 || rootCloseIdx === -1) {
  throw new Error('Could not locate .wb_root markup bounds in index.html — did the wrapper markup change?');
}
let fragmentHtml = html.slice(rootOpenIdx, rootCloseIdx + '\t</div>'.length);
// Scripts (and the comment explaining their load order) become the separate
// JS field, not part of the HTML field.
fragmentHtml = fragmentHtml.replace(
  /\n?\t*<!-- Letter content[\s\S]*?<script[^>]*><\/script>\n?\t*<script[^>]*><\/script>\n?/,
  '\n'
);
fragmentHtml = fragmentHtml.trim() + '\n';

// ── 2. CSS field: tokens.css + styles.css, PROTOTYPE-ONLY block stripped ──────
const tokensCss = readLF(path.join(ROOT, 'assets/css/tokens.css'));
let stylesCss    = readLF(path.join(ROOT, 'assets/css/styles.css'));
const cssProtoStart = stylesCss.indexOf('\t/* ─── PROTOTYPE-ONLY: persona switcher');
const cssProtoEnd   = stylesCss.indexOf('\n\n}', cssProtoStart); // the persona-switcher block's blank line + .wb_root's own closing brace
if (cssProtoStart === -1 || cssProtoEnd === -1) {
  throw new Error('Could not locate the PROTOTYPE-ONLY block in styles.css — did the markers move?');
}
stylesCss = stylesCss.slice(0, cssProtoStart) + stylesCss.slice(cssProtoEnd + 1); // +1 keeps the leading \n before the final }
// styles.css normally lives in assets/css/, so its own asset refs climb one
// level with ../img/. welcome-baby.css sits flat in final/, a sibling of
// final/assets/, so those refs need to drop the ../ — otherwise they resolve
// to a nonexistent final/../img/ once shipped (caught by loading preview.html
// for real: url('../img/pattern.png') 404'd as /img/pattern.png).
const relImgRefs = (stylesCss.match(/url\('\.\.\/img\//g) || []).length;
if (relImgRefs !== 2) throw new Error(`expected 2 '../img/' refs in styles.css, found ${relImgRefs} — update this rewrite if that count changed`);
stylesCss = stylesCss.replace(/url\('\.\.\/img\//g, "url('assets/img/");
const finalCss = `/* ${NAME} — Liferay fragment CSS field. GENERATED by scripts/build-final.mjs — do not hand-edit; edit assets/css/tokens.css or assets/css/styles.css and rebuild. */\n\n${tokensCss}\n${stylesCss}`;

// ── 3. JS field: content.js + app.js, PROTOTYPE-ONLY block stripped ───────────
const contentJs = readLF(path.join(ROOT, 'assets/js/content.js'));
let appJs        = readLF(path.join(ROOT, 'assets/js/app.js'));
const jsProtoStart = appJs.indexOf('// ── PROTOTYPE-ONLY: persona switcher');
const jsProtoEndMarker = '// ── END PROTOTYPE-ONLY ─────────────────────────────────────────────────────────\n';
const jsProtoEnd = appJs.indexOf(jsProtoEndMarker);
if (jsProtoStart === -1 || jsProtoEnd === -1) {
  throw new Error('Could not locate the PROTOTYPE-ONLY block in app.js — did the markers move?');
}
appJs = appJs.slice(0, jsProtoStart) + appJs.slice(jsProtoEnd + jsProtoEndMarker.length);
// One more prototype-only reference lives outside the marked block (the wheel
// handler letting the switcher panel scroll normally) — the switcher itself
// is gone, so this guard would be dead code (harmless — closest() just never
// matches — but no reason to ship it).
const wheelGuard = "    // Prototype-only control — let it scroll/behave normally.\n    if (e.target.closest && e.target.closest('.wb_persona-switcher')) return;\n";
if (!appJs.includes(wheelGuard)) throw new Error('wheel-handler persona-switcher guard not found — did it move?');
appJs = appJs.replace(wheelGuard, '');
const finalJs = `// ${NAME} — Liferay fragment JS field. GENERATED by scripts/build-final.mjs — do not hand-edit; edit assets/js/content.js or assets/js/app.js and rebuild.\n\n${contentJs}\n${appJs}`;

// ── 4. Assets: auto-detected from what the generated fields actually
//    reference, not hand-maintained — a hardcoded list here already went
//    stale twice (thumbs-up.svg, then stork-message.png shipped broken
//    image references because nobody remembered to add them to a list).
//    Scans all four source texts (contentJs feeds illustration paths that
//    never appear in appJs itself) for assets/img/<file>, case-sensitively
//    (gotchas #11 — GitHub Pages is a Linux filesystem).
const assetRefRe = /assets\/img\/([A-Za-z0-9_.-]+\.(?:png|jpg|jpeg|svg))/g;
const allRefs = [...[fragmentHtml, finalCss, contentJs, appJs].join('\n').matchAll(assetRefRe)].map((m) => m[1]);
const LIVE_ASSETS = [...new Set(allRefs)].sort();
for (const f of LIVE_ASSETS) {
  if (!fs.existsSync(path.join(ROOT, 'assets/img', f))) {
    throw new Error(`Referenced asset assets/img/${f} does not exist — typo, or case mismatch?`);
  }
}

// ── Write ───────────────────────────────────────────────────────────────────
fs.mkdirSync(path.join(OUT, 'assets/img'), { recursive: true });
fs.writeFileSync(path.join(OUT, `${NAME}.html`), fragmentHtml);
fs.writeFileSync(path.join(OUT, `${NAME}.css`), finalCss);
fs.writeFileSync(path.join(OUT, `${NAME}.js`), finalJs);
for (const f of LIVE_ASSETS) {
  fs.copyFileSync(path.join(ROOT, 'assets/img', f), path.join(OUT, 'assets/img', f));
}

console.log(`Wrote ${NAME}.html (${fragmentHtml.length} bytes)`);
console.log(`Wrote ${NAME}.css (${finalCss.length} bytes)`);
console.log(`Wrote ${NAME}.js (${finalJs.length} bytes)`);
console.log(`Copied ${LIVE_ASSETS.length} assets`);
console.log('README.md and preview.html are hand-maintained in final/ — not touched by this script.');
